### ISSUE TITLE
Skip Command Error

### ISSUE THREAD

**Issue by Jvkeh** [Tape-Dispenser/Immersive-Music-Mod#16]
When using /skip, the chat and game log throw a NullPointerExeption, stating  'Cannot invoke "Object.toString()" because "net.tape.timm.songControls.lastSong" is null'.

That variable is never being set. Is it only set once a song finishes? I haven't let a song play through to the end, so that could be the issue. If so, lastSong should likely be set when a new song begins to play, setting the variable to the previous song

**Comment by Jvkeh** [comment]
Just tested by letting the song finish, the value is still null

**Comment by Tape-Dispenser** [comment]
The issue lies in how `songControls.skip()` plays songs, if `songControls.play(Song)` is called, `songControls.lastSong` will be set to whatever song is passed to the function, but if `songControls.play(SoundEvent)` is called then `songControls.lastSong` will be set to null, as there is no way to determine what playlist the SoundEvent came from. I have fixed the issue now and it will be patched in 1.0.3. As this issue seems to just be a cosmetic one, i.e. an error log is printed to chat, but the game does not crash, and skipping songs still works, I will not be rushing to push a patch for this.
